name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test on JDK ${{ matrix.java }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Run tests
      shell: bash
      run: mvn clean test -Dmaven.gpg.skip=true
      
    - name: Generate test report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Maven Tests (${{ matrix.java }} on ${{ matrix.os }})
        path: '**/target/surefire-reports/*.xml'
        reporter: java-junit
        fail-on-error: true
        
    - name: Upload coverage to Codecov
      if: matrix.java == '21' && matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v5
      with:
        file: target/site/jacoco/jacoco.xml
        fail_ci_if_error: false

  build:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build and Package
      shell: bash
      run: mvn clean install -DskipTests -Dmaven.gpg.skip=true
      
    - name: Generate Javadoc
      shell: bash
      run: mvn javadoc:javadoc -Dmaven.gpg.skip=true
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          target/*.jar
          target/site/apidocs/
        retention-days: 30

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true  # Don't fail the workflow if SonarCloud fails
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Run SonarCloud analysis
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        if [ -z "$SONAR_TOKEN" ]; then
          echo "Skipping SonarCloud analysis - SONAR_TOKEN not configured"
        else
          echo "Running SonarCloud analysis..."
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=clojang_erlymcjface \
            -Dsonar.organization=clojang \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dmaven.gpg.skip=true || {
              echo "SonarCloud analysis failed. Common issues:"
              echo "1. Project 'clojang_erlymcjface' may not exist in SonarCloud"
              echo "2. Automatic Analysis may be enabled (disable it in project settings)"
              echo "3. SONAR_TOKEN may be invalid"
              echo "Visit: https://sonarcloud.io/projects"
              exit 1
            }
        fi

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build modules for dependency resolution
      run: mvn clean install -DskipTests -Dmaven.gpg.skip=true
      
    - name: Run OWASP Dependency Check
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      run: mvn org.owasp:dependency-check-maven:check -Dmaven.gpg.skip=true -Dnvd.api.key=$NVD_API_KEY

    - name: Upload dependency check results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-check-report
        path: target/dependency-check-report.html